FROM node:24-alpine

ENV NODE_ENV=development

WORKDIR /app
RUN chmod 777 /app

RUN apk add --no-cache git

USER node

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

EXPOSE 8080

CMD ["npm", "run", "start:dev"]
